### ISSUE TITLE
packageError: please install mysql2 package manually

### ISSUE THREAD

**Issue by santosh9991** [santosh9991/sequilize-node#1]
Installing sequelize by following the http://docs.sequelizejs.com/manual/installation/getting-started results in please install mysql2 package manually.

**Comment by santosh9991** [comment]
Reference to the issue explanation is found in https://github.com/sequelize/sequelize/issues/6546.
We can overcome the issue by installing mysql2 package, i.e npm install --save mysql2

**Comment by ayazhussain1** [comment]
Not working

**Comment by santosh9991** [comment]
@ayazhussain1 : What error do you get ?
